name: Build

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+*"

jobs:
  build:
    env:
      GHC_VERSION: "9.10.1"
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64-linux
          - os: macos-14
            arch: aarch64-darwin
    name: Build ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ env.GHC_VERSION }}
          cabal-version: "latest"

      - name: Cache Cabal store
        uses: actions/cache@v4
        with:
          path: |
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ runner.arch }}-ghc-${{ env.GHC_VERSION }}-${{ hashFiles('**/*.cabal') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-ghc-${{ env.GHC_VERSION }}-

      - name: Build dependencies
        run: cabal build --only-dependencies

      - name: Build project
        run: cabal build

      - name: Run tests
        run: cabal test

      - name: Create executable
        run: |
          mkdir -p dist
          cp "$(cabal list-bin trie-match)" dist/trie-match-${{ matrix.arch }}

      - name: Strip executable and compress with upx
        if: runner.os != 'macOS'
        uses: svenstaro/upx-action@2.4.1
        with:
          files: dist/trie-match-${{ matrix.arch }}

      - name: Strip executable
        if: runner.os == 'macOS'
        run: strip dist/trie-match-${{ matrix.arch }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: trie-match-${{ matrix.arch }}
          path: dist/trie-match-${{ matrix.arch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          draft: true
          files: |
            artifacts/trie-match-x86_64-linux/trie-match-x86_64-linux
            artifacts/trie-match-aarch64-darwin/trie-match-aarch64-darwin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
